name: Build And Test PredicateBuilder

on:
  push: 
    branches: [ main ]
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  predicate-builder-package-tests:
    name: XCTest | Xcode ${{ matrix.xcode-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        xcode-version: ["14.2", "14.3"]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./PredicateBuilder
    steps:
      - uses: actions/checkout@v3
      - name: Build Swift Package
        run: swift build
      - name: Run Tests
        run: swift test
      - name: Type Inference Tests | Xcode ${{ matrix.xcode-version }} on ${{ matrix.os }}
        working-directory: ./PredicateBuilder/CompilationTests/Tests/
        run: ./test-compilation.sh
  # predicate-builder-macro-package-tests:
  #   name: Test PredicateBuilderMacro Package | Xcode ${{ matrix.xcode-version }} on ${{ matrix.os }}
  #   runs-on: macos-13
  #   strategy: 
  #     matrix:
  #       xcode-version: ["15.0.0"]
  #   env:
  #     DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer"
  #   defaults:
  #     run:
  #       working-directory: ./PredicateBuilderMacro
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build Swift Package
  #       run: swift build
  #     - name: Run Tests
  #       run: swift test