name: Build And Test PredicateBuilder

on:
  push: 
    branches: [ main ]
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  predicate-builder-package-tests:
    name: XCTest | macOS Latest
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Build Swift Package
        run: swift build
      - name: Run Tests
        run: swift test
      - name: Public API Consumption Tests
        working-directory: ./ConsumptionTest
        run: |
          echo "Testing valid code compiles..."
          swift build --target ValidCode
          echo "Testing invalid code fails to compile..."
          ./Tests/test-compilation.sh